import Head from "next/head";
import TakeControl from "../../components/landingPageLayout/TakeControlSection";
import WhenYouFly from "../../components/landingPageLayout/GettheAwardSection";
import TravelTraking from "../../components/landingPageLayout/PilotGradeSection";
import SaveTime from "../../components/landingPageLayout/FlyLikeAProSection";
import HistoryRace from "../../components/landingPageLayout/TrackYourFlightSection";
import TrakedSupport from "../../components/landingPageLayout/TripTrackedSupportedSection";
import JoinSection from "../../components/landingPageLayout/WelcomeAboardSection";
import Reviews from "../../components/Common/Reviews";

export default function Home() {
  return (
    <>
      <Head>
        <title>App in the Air - Personal travel</title>
        <meta name="description" content="Generated by App in the Air" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TakeControl />
      <WhenYouFly />
      <TravelTraking />
      <SaveTime />
      <HistoryRace />
      <Reviews />
      <TrakedSupport />
      <JoinSection />
    </>
  );
}
